/**
 * State new-hire registry directory.
 * Each entry: where to submit + accepted formats. URLs/fax/mail are the
 * official channels published by each state's child-support enforcement unit.
 */

export type StateNewHireRegistry = {
  code: string;
  name: string;
  agency: string;
  submitUrl: string | null;
  fax: string | null;
  mail: string | null;
  acceptedFormats: ("Online" | "Mail" | "Fax" | "Magnetic" | "CSV/Electronic")[];
  notes?: string;
};

export const STATE_NEW_HIRE_REGISTRY: Record<string, StateNewHireRegistry> = {
  AL: { code: "AL", name: "Alabama", agency: "AL New Hire Reporting Center", submitUrl: "https://newhire-reporting.com/AL-Newhire/default.aspx", fax: "334-353-1797", mail: "Alabama New Hire Reporting Center, PO Box 5160, Norman, OK 73070", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  AK: { code: "AK", name: "Alaska", agency: "AK Child Support Services", submitUrl: "https://newhire.alaska.gov/", fax: "907-787-3197", mail: "Alaska New Hire Reporting, 550 W 7th Ave Ste 310, Anchorage, AK 99501", acceptedFormats: ["Online", "Fax", "Mail"] },
  AZ: { code: "AZ", name: "Arizona", agency: "AZ New Hire Reporting Center", submitUrl: "https://az-newhire.com/", fax: "888-282-0502", mail: "Arizona New Hire Reporting Center, PO Box 25458, Phoenix, AZ 85002", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  AR: { code: "AR", name: "Arkansas", agency: "AR New Hire Reporting Center", submitUrl: "https://ar-newhire.com/", fax: "800-259-3562", mail: "Arkansas New Hire Reporting Center, PO Box 2981, Little Rock, AR 72203", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  CA: { code: "CA", name: "California", agency: "CA EDD New Employee Registry", submitUrl: "https://edd.ca.gov/en/payroll_taxes/new_hire_reporting/", fax: "916-319-4400", mail: "Employment Development Dept, PO Box 997016 MIC 96, West Sacramento, CA 95799", acceptedFormats: ["Online", "Fax", "Mail", "Magnetic"], notes: "Use form DE 34 or electronic equivalent. Report within 20 days." },
  CO: { code: "CO", name: "Colorado", agency: "CO State Directory of New Hires", submitUrl: "https://newhire.state.co.us/", fax: "303-297-2595", mail: "Colorado State Directory of New Hires, PO Box 2920, Denver, CO 80201", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  CT: { code: "CT", name: "Connecticut", agency: "CT Dept of Labor", submitUrl: "https://www.ctnewhires.com/", fax: "800-816-1108", mail: "Connecticut Dept of Labor, Office of Research, 200 Folly Brook Blvd, Wethersfield, CT 06109", acceptedFormats: ["Online", "Fax", "Mail"] },
  DE: { code: "DE", name: "Delaware", agency: "DE Division of Child Support", submitUrl: "https://de-newhire.com/", fax: "855-481-0047", mail: "Delaware New Hire Reporting, PO Box 90370, Atlanta, GA 30364", acceptedFormats: ["Online", "Fax", "Mail"] },
  FL: { code: "FL", name: "Florida", agency: "FL New Hire Reporting Center", submitUrl: "https://services.myfloridacounty.com/childsupport/newhire/", fax: "888-854-4762", mail: "Florida New Hire Reporting Center, PO Box 6500, Tallahassee, FL 32314", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  GA: { code: "GA", name: "Georgia", agency: "GA New Hire Reporting Center", submitUrl: "https://ga-newhire.com/", fax: "404-525-2985", mail: "Georgia New Hire Reporting Program, PO Box 38480, Atlanta, GA 30334", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  HI: { code: "HI", name: "Hawaii", agency: "HI Child Support Enforcement", submitUrl: "https://huinet.dhs.hawaii.gov/", fax: "808-692-7001", mail: "Hawaii Child Support Enforcement Agency, Kakuhihewa Bldg, 601 Kamokila Blvd Ste 251, Kapolei, HI 96707", acceptedFormats: ["Online", "Fax", "Mail"] },
  ID: { code: "ID", name: "Idaho", agency: "ID Dept of Labor", submitUrl: "https://labor.idaho.gov/newhire/", fax: "208-332-7411", mail: "Idaho Dept of Labor, New Hire Reporting, 317 W Main St, Boise, ID 83735", acceptedFormats: ["Online", "Fax", "Mail"] },
  IL: { code: "IL", name: "Illinois", agency: "IL New Hire Directory", submitUrl: "https://il-newhire.com/", fax: "217-557-1947", mail: "Illinois New Hire Directory, PO Box 19473, Springfield, IL 62794", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  IN: { code: "IN", name: "Indiana", agency: "IN New Hire Reporting Center", submitUrl: "https://in-newhire.com/", fax: "800-408-1388", mail: "Indiana New Hire Reporting Center, PO Box 55097, Indianapolis, IN 46205", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  IA: { code: "IA", name: "Iowa", agency: "IA Centralized Employee Registry", submitUrl: "https://secureapp.dhs.state.ia.us/epay/", fax: "800-759-5881", mail: "Iowa Centralized Employee Registry, PO Box 10322, Des Moines, IA 50306", acceptedFormats: ["Online", "Fax", "Mail"] },
  KS: { code: "KS", name: "Kansas", agency: "KS New Hire Directory", submitUrl: "https://ks-newhire.com/", fax: "888-219-7798", mail: "Kansas New Hire Directory, PO Box 3510, Topeka, KS 66601", acceptedFormats: ["Online", "Fax", "Mail"] },
  KY: { code: "KY", name: "Kentucky", agency: "KY New Hire Reporting Center", submitUrl: "https://newhire-reporting.com/KY-Newhire/", fax: "800-817-1010", mail: "Kentucky New Hire Reporting Center, PO Box 1407, Norman, OK 73070", acceptedFormats: ["Online", "Fax", "Mail"] },
  LA: { code: "LA", name: "Louisiana", agency: "LA New Hire Reporting", submitUrl: "https://newhire-reporting.com/LA-Newhire/", fax: "800-688-2540", mail: "Louisiana New Hire Reporting, PO Box 142513, Austin, TX 78714", acceptedFormats: ["Online", "Fax", "Mail"] },
  ME: { code: "ME", name: "Maine", agency: "ME Division of Support Enforcement", submitUrl: "https://www.maine.gov/dhhs/ofi/dser/employer/new-hire-reporting", fax: "207-287-5396", mail: "DHHS New Hire Reporting, 11 State House Station, Augusta, ME 04333", acceptedFormats: ["Online", "Fax", "Mail"] },
  MD: { code: "MD", name: "Maryland", agency: "MD New Hire Registry", submitUrl: "https://md-newhire.com/", fax: "410-281-6004", mail: "Maryland State Directory of New Hires, PO Box 1316, Baltimore, MD 21203", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  MA: { code: "MA", name: "Massachusetts", agency: "MA Dept of Revenue, CSE", submitUrl: "https://www.mass.gov/new-hire-reporting", fax: "617-887-7560", mail: "MA Dept of Revenue, PO Box 55141, Boston, MA 02205", acceptedFormats: ["Online", "Fax", "Mail"] },
  MI: { code: "MI", name: "Michigan", agency: "MI New Hire Operations Center", submitUrl: "https://mi-newhire.com/", fax: "877-318-1659", mail: "Michigan New Hire Operations Center, PO Box 85010, Lansing, MI 48908", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  MN: { code: "MN", name: "Minnesota", agency: "MN New Hire Reporting Center", submitUrl: "https://mn-newhire.com/", fax: "800-692-4473", mail: "Minnesota New Hire Reporting Center, PO Box 64212, St Paul, MN 55164", acceptedFormats: ["Online", "Fax", "Mail"] },
  MS: { code: "MS", name: "Mississippi", agency: "MS New Hire Reporting Center", submitUrl: "https://ms-newhire.com/", fax: "800-937-8668", mail: "Mississippi State Directory of New Hires, PO Box 437, Norman, OK 73070", acceptedFormats: ["Online", "Fax", "Mail"] },
  MO: { code: "MO", name: "Missouri", agency: "MO Dept of Social Services", submitUrl: "https://www.mo-newhire.com/", fax: "573-526-8079", mail: "Missouri New Hire Reporting, PO Box 3340, Jefferson City, MO 65105", acceptedFormats: ["Online", "Fax", "Mail"] },
  MT: { code: "MT", name: "Montana", agency: "MT New Hire Reporting Program", submitUrl: "https://newhire-reporting.com/MT-Newhire/", fax: "888-272-1990", mail: "Montana New Hire Reporting, PO Box 8013, Helena, MT 59604", acceptedFormats: ["Online", "Fax", "Mail"] },
  NE: { code: "NE", name: "Nebraska", agency: "NE State Directory of New Hires", submitUrl: "https://ne-newhire.com/", fax: "888-256-0541", mail: "Nebraska State Directory of New Hires, PO Box 144013, Austin, TX 78714", acceptedFormats: ["Online", "Fax", "Mail"] },
  NV: { code: "NV", name: "Nevada", agency: "NV New Hire Reporting", submitUrl: "https://newhire-reporting.com/NV-Newhire/", fax: "775-684-8003", mail: "Nevada New Hire Reporting, PO Box 98664, Las Vegas, NV 89193", acceptedFormats: ["Online", "Fax", "Mail"] },
  NH: { code: "NH", name: "New Hampshire", agency: "NH Employment Security", submitUrl: "https://www.nhes.nh.gov/services/employers/newhire.htm", fax: "603-224-0825", mail: "NH Dept of Employment Security, New Hire Program, PO Box 2092, Concord, NH 03302", acceptedFormats: ["Online", "Fax", "Mail"] },
  NJ: { code: "NJ", name: "New Jersey", agency: "NJ New Hire Reporting Center", submitUrl: "https://nj-newhire.com/", fax: "800-304-4901", mail: "New Jersey New Hire Reporting Center, PO Box 4654, Trenton, NJ 08650", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  NM: { code: "NM", name: "New Mexico", agency: "NM New Hires Directory", submitUrl: "https://nm-newhire.com/", fax: "888-878-1614", mail: "New Mexico New Hires Directory, PO Box 2999, Roswell, NM 88202", acceptedFormats: ["Online", "Fax", "Mail"] },
  NY: { code: "NY", name: "New York", agency: "NY State Dept of Taxation & Finance", submitUrl: "https://www.tax.ny.gov/bus/wt/newhire.htm", fax: "518-320-1080", mail: "NYS Dept of Taxation and Finance, New Hire Notification, PO Box 15119, Albany, NY 12212", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"], notes: "Use form IT-2104 / IT-2104-E for tax withholding combined with hire reporting." },
  NC: { code: "NC", name: "North Carolina", agency: "NC New Hire Directory", submitUrl: "https://nc-newhire.com/", fax: "866-257-7005", mail: "NC New Hire Reporting, PO Box 90369, East Point, GA 30364", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  ND: { code: "ND", name: "North Dakota", agency: "ND Child Support Enforcement", submitUrl: "https://www.childsupport.dhs.nd.gov/employer/newhire", fax: "701-328-5497", mail: "ND New Hire Reporting, PO Box 7369, Bismarck, ND 58507", acceptedFormats: ["Online", "Fax", "Mail"] },
  OH: { code: "OH", name: "Ohio", agency: "OH New Hire Reporting Center", submitUrl: "https://oh-newhire.com/", fax: "888-872-1611", mail: "Ohio New Hire Reporting Center, PO Box 15309, Columbus, OH 43215", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  OK: { code: "OK", name: "Oklahoma", agency: "OK New Hire Reporting Center", submitUrl: "https://newhire-reporting.com/OK-Newhire/", fax: "800-317-3786", mail: "Oklahoma New Hire Reporting Center, PO Box 52003, Oklahoma City, OK 73152", acceptedFormats: ["Online", "Fax", "Mail"] },
  OR: { code: "OR", name: "Oregon", agency: "OR Dept of Justice, Division of Child Support", submitUrl: "https://justice.oregon.gov/employers/", fax: "877-877-7415", mail: "Oregon Dept of Justice, Division of Child Support, 4600 25th Ave NE Ste 180, Salem, OR 97301", acceptedFormats: ["Online", "Fax", "Mail"] },
  PA: { code: "PA", name: "Pennsylvania", agency: "PA Commonwealth of PA New Hire Program", submitUrl: "https://www.cwds.pa.gov/Newhire/", fax: "866-748-4473", mail: "Commonwealth of PA New Hire Program, PO Box 69400, Harrisburg, PA 17106", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  RI: { code: "RI", name: "Rhode Island", agency: "RI New Hire Reporting Directory", submitUrl: "https://ri-newhire.com/", fax: "888-430-6907", mail: "Rhode Island New Hire Reporting, PO Box 335, Holbrook, MA 02343", acceptedFormats: ["Online", "Fax", "Mail"] },
  SC: { code: "SC", name: "South Carolina", agency: "SC New Hire Reporting Program", submitUrl: "https://newhire.sc.gov/", fax: "803-936-2867", mail: "SC Dept of Social Services, New Hire Reporting Program, PO Box 1469, Columbia, SC 29202", acceptedFormats: ["Online", "Fax", "Mail"] },
  SD: { code: "SD", name: "South Dakota", agency: "SD New Hire Reporting Center", submitUrl: "https://sd-newhire.com/", fax: "888-835-8659", mail: "South Dakota New Hire Reporting Center, PO Box 4700, Aberdeen, SD 57402", acceptedFormats: ["Online", "Fax", "Mail"] },
  TN: { code: "TN", name: "Tennessee", agency: "TN New Hire Reporting Operations Center", submitUrl: "https://tn-newhire.com/", fax: "877-505-4761", mail: "Tennessee New Hire Reporting Operations Center, PO Box 17367, Nashville, TN 37217", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  TX: { code: "TX", name: "Texas", agency: "TX Employer New Hire Reporting Operations Center", submitUrl: "https://portal.cs.oag.state.tx.us/wps/portal/employer/", fax: "800-732-5015", mail: "ENHR Operations Center, PO Box 149224, Austin, TX 78714", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  UT: { code: "UT", name: "Utah", agency: "UT New Hire Registry", submitUrl: "https://jobs.utah.gov/ui/employer/Public/newhire.aspx", fax: "801-526-4391", mail: "Utah New Hire Registry, PO Box 45247, Salt Lake City, UT 84145", acceptedFormats: ["Online", "Fax", "Mail"] },
  VT: { code: "VT", name: "Vermont", agency: "VT New Hire Reporting", submitUrl: "https://labor.vermont.gov/newhire", fax: "802-828-4286", mail: "Vermont Dept of Labor, New Hire Reporting Program, PO Box 488, Montpelier, VT 05601", acceptedFormats: ["Online", "Fax", "Mail"] },
  VA: { code: "VA", name: "Virginia", agency: "VA New Hire Reporting Center", submitUrl: "https://va-newhire.com/", fax: "800-688-2680", mail: "Virginia New Hire Reporting Center, PO Box 25309, Richmond, VA 23260", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  WA: { code: "WA", name: "Washington", agency: "WA Division of Child Support", submitUrl: "https://www.dshs.wa.gov/esa/division-child-support/employer-new-hire-reporting", fax: "800-782-0624", mail: "DSHS Division of Child Support, New Hire Reporting, PO Box 9162, Olympia, WA 98507", acceptedFormats: ["Online", "Fax", "Mail"] },
  WV: { code: "WV", name: "West Virginia", agency: "WV New Hire Reporting Center", submitUrl: "https://wv-newhire.com/", fax: "877-625-4675", mail: "WV New Hire Reporting Center, PO Box 2998, Charleston, WV 25330", acceptedFormats: ["Online", "Fax", "Mail"] },
  WI: { code: "WI", name: "Wisconsin", agency: "WI New Hire Reporting Center", submitUrl: "https://wi-newhire.com/", fax: "800-277-8075", mail: "Wisconsin New Hire Reporting, PO Box 14431, Madison, WI 53708", acceptedFormats: ["Online", "Fax", "Mail", "CSV/Electronic"] },
  WY: { code: "WY", name: "Wyoming", agency: "WY New Hire Reporting Center", submitUrl: "https://newhire-reporting.com/WY-Newhire/", fax: "800-921-9651", mail: "Wyoming New Hire Reporting Center, PO Box 1408, Cheyenne, WY 82003", acceptedFormats: ["Online", "Fax", "Mail"] },
  DC: { code: "DC", name: "District of Columbia", agency: "DC New Hire Registry", submitUrl: "https://newhire-reporting.com/DC-Newhire/", fax: "877-746-9415", mail: "DC New Hire Registry Operations Center, PO Box 366, Holbrook, MA 02343", acceptedFormats: ["Online", "Fax", "Mail"] },
};

export function getStateRegistry(code: string | null | undefined): StateNewHireRegistry | null {
  if (!code) return null;
  return STATE_NEW_HIRE_REGISTRY[code.toUpperCase()] ?? null;
}
