/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTimeRouteImport } from './routes/app.time'
import { Route as AppTaxesRouteImport } from './routes/app.taxes'
import { Route as AppTaxFilingRouteImport } from './routes/app.tax-filing'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPtoRouteImport } from './routes/app.pto'
import { Route as AppPaystubsRouteImport } from './routes/app.paystubs'
import { Route as AppPayrollRouteImport } from './routes/app.payroll'
import { Route as AppGettingStartedRouteImport } from './routes/app.getting-started'
import { Route as AppForm1099RouteImport } from './routes/app.form-1099'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppContractorsRouteImport } from './routes/app.contractors'
import { Route as AppBenefitsRouteImport } from './routes/app.benefits'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimeRoute = AppTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxesRoute = AppTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxFilingRoute = AppTaxFilingRouteImport.update({
  id: '/tax-filing',
  path: '/tax-filing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPtoRoute = AppPtoRouteImport.update({
  id: '/pto',
  path: '/pto',
  getParentRoute: () => AppRoute,
} as any)
const AppPaystubsRoute = AppPaystubsRouteImport.update({
  id: '/paystubs',
  path: '/paystubs',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppGettingStartedRoute = AppGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => AppRoute,
} as any)
const AppForm1099Route = AppForm1099RouteImport.update({
  id: '/form-1099',
  path: '/form-1099',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContractorsRoute = AppContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => AppRoute,
} as any)
const AppBenefitsRoute = AppBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/benefits': typeof AppBenefitsRoute
  '/app/contractors': typeof AppContractorsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/form-1099': typeof AppForm1099Route
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/paystubs': typeof AppPaystubsRoute
  '/app/pto': typeof AppPtoRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tax-filing': typeof AppTaxFilingRoute
  '/app/taxes': typeof AppTaxesRoute
  '/app/time': typeof AppTimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/benefits': typeof AppBenefitsRoute
  '/app/contractors': typeof AppContractorsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/form-1099': typeof AppForm1099Route
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/paystubs': typeof AppPaystubsRoute
  '/app/pto': typeof AppPtoRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tax-filing': typeof AppTaxFilingRoute
  '/app/taxes': typeof AppTaxesRoute
  '/app/time': typeof AppTimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/benefits': typeof AppBenefitsRoute
  '/app/contractors': typeof AppContractorsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/form-1099': typeof AppForm1099Route
  '/app/getting-started': typeof AppGettingStartedRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/paystubs': typeof AppPaystubsRoute
  '/app/pto': typeof AppPtoRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tax-filing': typeof AppTaxFilingRoute
  '/app/taxes': typeof AppTaxesRoute
  '/app/time': typeof AppTimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/benefits'
    | '/app/contractors'
    | '/app/dashboard'
    | '/app/employees'
    | '/app/form-1099'
    | '/app/getting-started'
    | '/app/payroll'
    | '/app/paystubs'
    | '/app/pto'
    | '/app/reports'
    | '/app/settings'
    | '/app/tax-filing'
    | '/app/taxes'
    | '/app/time'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/benefits'
    | '/app/contractors'
    | '/app/dashboard'
    | '/app/employees'
    | '/app/form-1099'
    | '/app/getting-started'
    | '/app/payroll'
    | '/app/paystubs'
    | '/app/pto'
    | '/app/reports'
    | '/app/settings'
    | '/app/tax-filing'
    | '/app/taxes'
    | '/app/time'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/benefits'
    | '/app/contractors'
    | '/app/dashboard'
    | '/app/employees'
    | '/app/form-1099'
    | '/app/getting-started'
    | '/app/payroll'
    | '/app/paystubs'
    | '/app/pto'
    | '/app/reports'
    | '/app/settings'
    | '/app/tax-filing'
    | '/app/taxes'
    | '/app/time'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/time': {
      id: '/app/time'
      path: '/time'
      fullPath: '/app/time'
      preLoaderRoute: typeof AppTimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/taxes': {
      id: '/app/taxes'
      path: '/taxes'
      fullPath: '/app/taxes'
      preLoaderRoute: typeof AppTaxesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tax-filing': {
      id: '/app/tax-filing'
      path: '/tax-filing'
      fullPath: '/app/tax-filing'
      preLoaderRoute: typeof AppTaxFilingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pto': {
      id: '/app/pto'
      path: '/pto'
      fullPath: '/app/pto'
      preLoaderRoute: typeof AppPtoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/paystubs': {
      id: '/app/paystubs'
      path: '/paystubs'
      fullPath: '/app/paystubs'
      preLoaderRoute: typeof AppPaystubsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll': {
      id: '/app/payroll'
      path: '/payroll'
      fullPath: '/app/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/getting-started': {
      id: '/app/getting-started'
      path: '/getting-started'
      fullPath: '/app/getting-started'
      preLoaderRoute: typeof AppGettingStartedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/form-1099': {
      id: '/app/form-1099'
      path: '/form-1099'
      fullPath: '/app/form-1099'
      preLoaderRoute: typeof AppForm1099RouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contractors': {
      id: '/app/contractors'
      path: '/contractors'
      fullPath: '/app/contractors'
      preLoaderRoute: typeof AppContractorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/benefits': {
      id: '/app/benefits'
      path: '/benefits'
      fullPath: '/app/benefits'
      preLoaderRoute: typeof AppBenefitsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBenefitsRoute: typeof AppBenefitsRoute
  AppContractorsRoute: typeof AppContractorsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppForm1099Route: typeof AppForm1099Route
  AppGettingStartedRoute: typeof AppGettingStartedRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPaystubsRoute: typeof AppPaystubsRoute
  AppPtoRoute: typeof AppPtoRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTaxFilingRoute: typeof AppTaxFilingRoute
  AppTaxesRoute: typeof AppTaxesRoute
  AppTimeRoute: typeof AppTimeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBenefitsRoute: AppBenefitsRoute,
  AppContractorsRoute: AppContractorsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppForm1099Route: AppForm1099Route,
  AppGettingStartedRoute: AppGettingStartedRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPaystubsRoute: AppPaystubsRoute,
  AppPtoRoute: AppPtoRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTaxFilingRoute: AppTaxFilingRoute,
  AppTaxesRoute: AppTaxesRoute,
  AppTimeRoute: AppTimeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
