/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTimeRouteImport } from './routes/app.time'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPayrollRouteImport } from './routes/app.payroll'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimeRoute = AppTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/reports': typeof AppReportsRoute
  '/app/time': typeof AppTimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/reports': typeof AppReportsRoute
  '/app/time': typeof AppTimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/reports': typeof AppReportsRoute
  '/app/time': typeof AppTimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/app/employees'
    | '/app/payroll'
    | '/app/reports'
    | '/app/time'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/app/employees'
    | '/app/payroll'
    | '/app/reports'
    | '/app/time'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/app/employees'
    | '/app/payroll'
    | '/app/reports'
    | '/app/time'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/time': {
      id: '/app/time'
      path: '/time'
      fullPath: '/app/time'
      preLoaderRoute: typeof AppTimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll': {
      id: '/app/payroll'
      path: '/payroll'
      fullPath: '/app/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTimeRoute: typeof AppTimeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppReportsRoute: AppReportsRoute,
  AppTimeRoute: AppTimeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
